version: '3.3'
services:
  app:
    build: ./.docker/app
    ports:
      - '1234:1234'
    volumes:
      - ./:/app
    tty: true

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - ./volumes/db:/var/lib/mysql
    ports:
      - '3306:3306'
